In [3]:
import torch
import numpy as np

np.random.seed(1)

import os, sys
m_path = os.path.abspath(os.path.join(".."))
if m_path not in sys.path:
    sys.path.append(m_path)

c:\Users\skyfl\.conda\envs\data_sci\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [18]:
from xcloth.components.encoder import Encoder

shared_enc = Encoder()

In [19]:
from xcloth.components.sampling import build_sampling_layers, ConvDownSampling

# t = build_sampling_layers(
#     ConvDownSampling, 64, 3, 2, 2
# )

t = ConvDownSampling(64, 3)
print(t)
test_x = torch.Tensor(np.random.random((1, 64, 512, 512)))
t(test_x)

ConvDownSampling(
  (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (norm): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (activation): ReLU(inplace=True)
)


tensor([[[[1.9600e+00, 5.3775e-01, 3.9206e-01,  ..., 3.1893e-03,
           5.7747e-01, 0.0000e+00],
          [2.1664e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [1.0038e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 4.8823e-01],
          ...,
          [2.9932e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           6.2608e-01, 0.0000e+00],
          [1.2210e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 6.3636e-02],
          [0.0000e+00, 1.0854e+00, 0.0000e+00,  ..., 1.0034e+00,
           1.6886e+00, 0.0000e+00]],

         [[1.3769e+00, 1.8512e+00, 1.4120e+00,  ..., 1.7533e+00,
           1.6579e+00, 2.8111e+00],
          [4.4268e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 7.0290e-01],
          [1.3785e+00, 4.8810e-01, 9.0251e-01,  ..., 0.0000e+00,
           0.0000e+00, 5.9862e-01],
          ...,
          [7.7071e-01, 0.0000e+00, 0.0000e+00,  ..., 1.1106

In [4]:
test_x = torch.Tensor(np.random.random((4, 512, 512)))
test_x

tensor([[[0.5740, 0.5396, 0.0502,  ..., 0.2481, 0.4747, 0.8183],
         [0.1873, 0.2236, 0.3850,  ..., 0.9907, 0.5986, 0.6562],
         [0.5847, 0.8737, 0.6943,  ..., 0.2625, 0.9006, 0.0972],
         ...,
         [0.9083, 0.9553, 0.8996,  ..., 0.0762, 0.7806, 0.2407],
         [0.8170, 0.7560, 0.2434,  ..., 0.7512, 0.1368, 0.4406],
         [0.1650, 0.5508, 0.2480,  ..., 0.1616, 0.1395, 0.3958]],

        [[0.6302, 0.4014, 0.0293,  ..., 0.7782, 0.7711, 0.4987],
         [0.3310, 0.7213, 0.7662,  ..., 0.0817, 0.4991, 0.6109],
         [0.3627, 0.9505, 0.5200,  ..., 0.4299, 0.2510, 0.3201],
         ...,
         [0.5977, 0.9862, 0.3209,  ..., 0.9485, 0.1235, 0.8796],
         [0.3146, 0.0865, 0.6156,  ..., 0.1853, 0.6330, 0.5481],
         [0.4614, 0.1814, 0.3649,  ..., 0.5949, 0.4866, 0.9520]],

        [[0.5531, 0.2648, 0.1227,  ..., 0.7683, 0.2067, 0.2524],
         [0.8197, 0.7022, 0.4613,  ..., 0.6626, 0.7867, 0.5269],
         [0.6006, 0.7050, 0.3127,  ..., 0.9765, 0.0483, 0.

In [5]:
shared_enc(test_x, test_x).shape

torch.Size([1, 256, 128, 128])

In [20]:
from xcloth.components.decoder import DepthDecoder, NormDecoder, RGBDecoder

decoder_d = DepthDecoder()
decoder_n = NormDecoder()
decoder_rgb = RGBDecoder()


test_out = torch.Tensor(np.random.random((1, 256, 128, 128)))
print(decoder_d(test_out).shape,
      decoder_n(test_out).shape,
      decoder_rgb(test_out).shape,
)

torch.Size([1, 4, 512, 512]) torch.Size([1, 12, 512, 512]) torch.Size([1, 12, 512, 512])


In [4]:
from xcloth.production import Camera

np.random.seed(1)

camera = Camera()
rand = torch.Tensor(np.random.random((1, 4, 1, 512, 512)))
camera = Camera()
result = camera.project(rand)

In [5]:
rand[0, 0, 0, 187, 296]

tensor(0.5332)

In [6]:
result[0, 0, :, 187, 296]

tensor([ 2.1328e+03, -3.6790e+03,  5.3319e-01])